using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace MilwaukeeBeerCraft.Models
{
    public class BeerStyles
    {

        public virtual int Id
        { get; set; }
        public virtual string Name
        { get; set;}
        public virtual string UrlSlug
        { get; set; }
        public virtual bool AmericanAmber
        { get; set; }
        public virtual bool RedAle
        { get; set; }
        public virtual bool AmericanBarleywine
        { get; set; }
        public virtual bool AmericanBlackAle
        { get; set; }
        public virtual bool AmericanBlondeAle
        { get; set; }
        public virtual bool AmericanBrownAle
        { get; set; }
        public virtual bool AmericanDarkWheatAle
        { get; set; }
        public virtual bool AmericanDoubleIPA
        { get; set; }
        public virtual bool ImperialIPA
        { get; set; }
        public virtual bool AmericanDoubleStout
        { get; set; }
        public virtual bool ImperialStout
        { get; set; }
        public virtual bool AmericanIPA
        { get; set; }
        public virtual bool AmericanPaleAle
        { get; set; }
        public virtual bool AmericanPaleWheatAle
        { get; set; }
        public virtual bool AmericanPorter
        { get; set; }
        public virtual bool AmericanStout
        { get; set; }
        public virtual bool AmericanStrongAle
        { get; set; }
        public virtual bool AmericanWildAle
        { get; set; }
        public virtual bool BlackTan
        { get; set; }
        public virtual bool ChileBeer
        { get; set; }
        public virtual bool CreamAle
        { get; set; }
        public virtual bool PumpkinAle
        { get; set; }
        public virtual bool RyeBeer
        { get; set; }
        public virtual bool Wheatwine
        { get; set; }
        public virtual bool BelgianDarkAle
        { get; set; }
        public virtual bool BelgianIPA
        { get; set; }
        public virtual bool BelgianPaleAle
        { get; set; }
        public virtual bool BelgianStrongDarkAle
        { get; set; }
        public virtual bool BelgianStrongPaleAle
        { get; set; }
        public virtual bool BièredeGarde
        { get; set; }
        public virtual bool Dubbel
        { get; set; }
        public virtual bool Faro
        { get; set; }
        public virtual bool FlandersOudBruin
        { get; set; }
        public virtual bool FlandersRedAle
        { get; set; }
        public virtual bool Gueuze
        { get; set; }
        public virtual bool LambicFruit
        { get; set; }
        public virtual bool LambicUnblended
        { get; set; }
        public virtual bool Quadrupel
        { get; set; }
        public virtual bool Saison
        { get; set; }
        public virtual bool FarmhouseAle
        { get; set; }
        public virtual bool Tripel
        { get; set; }
        public virtual bool Witbier
        { get; set; }
        public virtual bool BalticPorter
        { get; set; }
        public virtual bool Braggot
        { get; set; }
        public virtual bool EnglishBarleywine
        { get; set; }
        public virtual bool EnglishBitter
        { get; set; }
        public virtual bool EnglishBrownAle
        { get; set; }
        public virtual bool EnglishDarkMildAle
        { get; set; }
        public virtual bool EnglishIndiaPaleAle
        { get; set; }
        public virtual bool EnglishPaleAle
        { get; set; }
        public virtual bool EnglishPaleMildAle
        { get; set; }
        public virtual bool EnglishPorter
        { get; set; }
        public virtual bool EnglishStout
        { get; set; }
        public virtual bool EnglishStrongAle
        { get; set; }
        public virtual bool ExtraSpecialBitter
        { get; set; }
        public virtual bool ExportStout
        { get; set; }
        public virtual bool MilkStout
        { get; set; }
        public virtual bool OatmealStout
        { get; set; }
        public virtual bool OldAle
        { get; set; }
        public virtual bool RussianImperialStout
        { get; set; }
        public virtual bool WinterWarmer
        { get; set; }
        public virtual bool Sahti
        { get; set; }
        public virtual bool Altbier
        { get; set; }
        public virtual bool BerlinerWeissbier
        { get; set; }
        public virtual bool Dunkelweizen
        { get; set; }
        public virtual bool Gose
        { get; set; }
        public virtual bool Hefeweizen
        { get; set; }
        public virtual bool Kölsch
        { get; set; }
        public virtual bool Kristalweizen
        { get; set; }
        public virtual bool Roggenbier
        { get; set; }
        public virtual bool Weizenbock
        { get; set; }
        public virtual bool IrishDryStout
        { get; set; }
        public virtual bool IrishRed
        { get; set; }
        public virtual bool Kvass
        { get; set; }
        public virtual bool ScotchAle
        { get; set; }
        public virtual bool WeeHeavy
        { get; set; }
        public virtual bool ScottishAle
        { get; set; }
        public virtual bool Gruit
        { get; set; }
        public virtual bool AncientHerbedAle
        { get; set; }
        public virtual bool AmericanAdjunctLager
        { get; set; }
        public virtual bool AmericanAmberLager
        { get; set; }
        public virtual bool AmericanRedLager
        { get; set; }
        public virtual bool AmericanImperialPilsner
        { get; set; }
        public virtual bool AmericanMaltLiquor
        { get; set; }
        public virtual bool AmericanPaleLager
        { get; set; }
        public virtual bool CaliforniaCommonSteamBeer
        { get; set; }
        public virtual bool LightLager
        { get; set; }
        public virtual bool CzechPilsener
        { get; set; }
        public virtual bool EuroDarkLager
        { get; set; }
        public virtual bool EuroPaleLager
        { get; set; }
        public virtual bool EuroStrongLager
        { get; set; }
        public virtual bool Bock
        { get; set; }
        public virtual bool Doppelbock
        { get; set; }
        public virtual bool Dortmunder
        { get; set; }
        public virtual bool Eisbock
        { get; set; }
        public virtual bool GermanPilsener
        { get; set; }
        public virtual bool KellerbierZwickelbier
            { get; set; }
        public virtual bool MaibockHellesBock
        { get; set; }
        public virtual bool MärzenOktoberfest
        { get; set; }
        public virtual bool MunichDunkelLager
        { get; set; }
        public virtual bool MunichHellesLager
        { get; set; }
        public virtual bool Rauchbier
        { get; set; }
        public virtual bool Schwarzbier
        { get; set; }
        public virtual bool ViennaLager
        { get; set; }
        public virtual bool FruitBeer
        { get; set; }
        public virtual bool HerbedBeer
        { get; set; }
        public virtual bool SmokedBeer
        { get; set; }
        public virtual ICollection<Post> Posts
        { get; set; }
    }
}